# Generated by Django 3.2.3 on 2021-05-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=2)),
                ("english_word", models.CharField(max_length=20)),
                ("lang_word", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("lang", "english_word"), name="lang_english_word"
            ),
        ),
    ]
